apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-backup-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - RWX
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.197
    path: /srv/nfs/mariadb/backups
